"""v2

Revision ID: 9c82c274bfe7
Revises: eb13dfb3c3f2
Create Date: 2024-12-09 16:39:01.963254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c82c274bfe7'
down_revision: Union[str, None] = 'eb13dfb3c3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('answer', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Task')),
    sa.UniqueConstraint('id', name=op.f('uq_Task_id'))
    )
    op.create_table('UserTask',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], name=op.f('fk_UserTask_taskId_Task')),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserTask_userId_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserTask')),
    sa.UniqueConstraint('id', name=op.f('uq_UserTask_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserTask')
    op.drop_table('Task')
    # ### end Alembic commands ###
