"""v6

Revision ID: fbc554bd875d
Revises: af7a2ac76fec
Create Date: 2025-10-04 09:54:34.418606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc554bd875d'
down_revision: Union[str, Sequence[str], None] = 'af7a2ac76fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Msg_reply_to_id_Msg'), 'Msg', ['reply_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Msg_reply_to_id_Msg'), type_='foreignkey')
        batch_op.drop_column('reply_to_id')

    # ### end Alembic commands ###
