"""v4

Revision ID: dc765efb240b
Revises: 7ebd822548bc
Create Date: 2025-06-05 17:08:32.684088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc765efb240b'
down_revision: Union[str, None] = '7ebd822548bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.alter_column('cmd',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('cmd',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
