"""v1

Revision ID: fe38ac74cfdc
Revises: 
Create Date: 2025-09-13 17:12:20.192466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe38ac74cfdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Log',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('actionCode', sa.String(length=16), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('tableName', sa.String(length=16), nullable=False),
    sa.Column('recordId', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Log')),
    sa.UniqueConstraint('id', name=op.f('uq_Log_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Msg',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_thread_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Msg')),
    sa.UniqueConstraint('id', name=op.f('uq_Msg_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Operation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Operation')),
    sa.UniqueConstraint('id', name=op.f('uq_Operation_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Role',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Role')),
    sa.UniqueConstraint('id', name=op.f('uq_Role_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Screamer',
    sa.Column('cmd', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Screamer')),
    sa.UniqueConstraint('id', name=op.f('uq_Screamer_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('User',
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_friendly', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('coins', sa.Integer(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User')),
    sa.UniqueConstraint('id', name=op.f('uq_User_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_id_tg'), ['id_tg'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_login'), ['login'], unique=True)

    op.create_table('Image',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('deletionDate', sa.DateTime(), nullable=True),
    sa.Column('createdById', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['createdById'], ['User.id'], name=op.f('fk_Image_createdById_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Image')),
    sa.UniqueConstraint('id', name=op.f('uq_Image_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Permission',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('operationId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['operationId'], ['Operation.id'], name=op.f('fk_Permission_operationId_Operation')),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name=op.f('fk_Permission_roleId_Role')),
    sa.PrimaryKeyConstraint('roleId', 'operationId', name=op.f('pk_Permission')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Queue',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_next_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['Msg.id'], name=op.f('fk_Queue_msg_id_Msg')),
    sa.ForeignKeyConstraint(['msg_next_id'], ['Msg.id'], name=op.f('fk_Queue_msg_next_id_Msg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Queue')),
    sa.UniqueConstraint('id', name=op.f('uq_Queue_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Tagger',
    sa.Column('cmd', sa.String(length=1024), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Tagger_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tagger')),
    sa.UniqueConstraint('id', name=op.f('uq_Tagger_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('TicTacToe',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['Msg.id'], name=op.f('fk_TicTacToe_msg_id_Msg')),
    sa.ForeignKeyConstraint(['player1_id'], ['User.id'], name=op.f('fk_TicTacToe_player1_id_User')),
    sa.ForeignKeyConstraint(['player2_id'], ['User.id'], name=op.f('fk_TicTacToe_player2_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TicTacToe')),
    sa.UniqueConstraint('id', name=op.f('uq_TicTacToe_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Transaction',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['User.id'], name=op.f('fk_Transaction_from_id_User')),
    sa.ForeignKeyConstraint(['to_id'], ['User.id'], name=op.f('fk_Transaction_to_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Transaction')),
    sa.UniqueConstraint('id', name=op.f('uq_Transaction_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('UserRole',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name=op.f('fk_UserRole_roleId_Role')),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserRole_userId_User')),
    sa.PrimaryKeyConstraint('userId', 'roleId', name=op.f('pk_UserRole')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('QueueUser',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enter_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['Queue.id'], name=op.f('fk_QueueUser_queue_id_Queue')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_QueueUser_user_id_User')),
    sa.PrimaryKeyConstraint('queue_id', 'user_id', name=op.f('pk_QueueUser')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QueueUser')
    op.drop_table('UserRole')
    op.drop_table('Transaction')
    op.drop_table('TicTacToe')
    op.drop_table('Tagger')
    op.drop_table('Queue')
    op.drop_table('Permission')
    op.drop_table('Image')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_login'))
        batch_op.drop_index(batch_op.f('ix_User_id_tg'))

    op.drop_table('User')
    op.drop_table('Screamer')
    op.drop_table('Role')
    op.drop_table('Operation')
    op.drop_table('Msg')
    op.drop_table('Log')
    # ### end Alembic commands ###
