"""v6

Revision ID: a9648e5fb60a
Revises: 41e5ef879a86
Create Date: 2025-06-08 18:46:17.147099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9648e5fb60a'
down_revision: Union[str, None] = '41e5ef879a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TicTacToe',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['Msg.id'], name=op.f('fk_TicTacToe_msg_id_Msg')),
    sa.ForeignKeyConstraint(['player1_id'], ['User.id'], name=op.f('fk_TicTacToe_player1_id_User')),
    sa.ForeignKeyConstraint(['player2_id'], ['User.id'], name=op.f('fk_TicTacToe_player2_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TicTacToe')),
    sa.UniqueConstraint('id', name=op.f('uq_TicTacToe_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Transaction',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['User.id'], name=op.f('fk_Transaction_from_id_User')),
    sa.ForeignKeyConstraint(['to_id'], ['User.id'], name=op.f('fk_Transaction_to_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Transaction')),
    sa.UniqueConstraint('id', name=op.f('uq_Transaction_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_Screamer2_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_Screamer_id'), ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), server_default='100', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('coins')

    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Screamer_id'), type_='unique')
        batch_op.create_unique_constraint('uq_Screamer2_id', ['id'])

    op.drop_table('Transaction')
    op.drop_table('TicTacToe')
    # ### end Alembic commands ###
