"""v5

Revision ID: 41e5ef879a86
Revises: dc765efb240b
Create Date: 2025-06-05 23:12:37.722766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text
from data.screamer import Screamer

# revision identifiers, used by Alembic.
revision: str = '41e5ef879a86'
down_revision: Union[str, None] = 'dc765efb240b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    screamers = list(session.execute(text("Select id, cmd, text From Screamer")))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Screamer')
    op.create_table('Screamer',
    sa.Column('cmd', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Screamer2')),
    sa.UniqueConstraint('id', name=op.f('uq_Screamer2_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###

    print(screamers)
    for (id, cmd, txt) in screamers:
        session.add(Screamer(id=id, cmd=cmd, text=txt))
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Screamer',
    sa.Column('cmd', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('text', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_Screamer_id')
    )
    op.drop_table('Screamer2')
    # ### end Alembic commands ###
