"""v4

Revision ID: b844949c075e
Revises: 08bdebfccf4d
Create Date: 2025-09-25 16:23:54.797011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b844949c075e'
down_revision: Union[str, Sequence[str], None] = '08bdebfccf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Misc', schema=None) as batch_op:
        batch_op.alter_column('os418_chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Misc', schema=None) as batch_op:
        batch_op.alter_column('os418_chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
