"""v8

Revision ID: ea913ff7d4ce
Revises: 4bea6923db72
Create Date: 2025-10-05 19:10:37.474711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea913ff7d4ce'
down_revision: Union[str, Sequence[str], None] = '4bea6923db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Curse',
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Curse_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Curse')),
    sa.UniqueConstraint('id', name=op.f('uq_Curse_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Curse')
    # ### end Alembic commands ###
