"""v7

Revision ID: 4bea6923db72
Revises: fbc554bd875d
Create Date: 2025-10-04 11:08:36.411298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bea6923db72'
down_revision: Union[str, Sequence[str], None] = 'fbc554bd875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Checker',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cmd', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['Msg.id'], name=op.f('fk_Checker_msg_id_Msg')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Checker_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Checker')),
    sa.UniqueConstraint('id', name=op.f('uq_Checker_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Checker')
    # ### end Alembic commands ###
