"""v3

Revision ID: 08bdebfccf4d
Revises: 8c9df9ec829a
Create Date: 2025-09-25 16:13:36.142110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bdebfccf4d'
down_revision: Union[str, Sequence[str], None] = '8c9df9ec829a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Misc',
    sa.Column('os418_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('os418_chat_thread_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Misc')),
    sa.UniqueConstraint('id', name=op.f('uq_Misc_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Misc')
    # ### end Alembic commands ###
