"""v3

Revision ID: 7ebd822548bc
Revises: d7dd14e386ef
Create Date: 2025-06-04 16:32:46.568182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebd822548bc'
down_revision: Union[str, None] = 'd7dd14e386ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Screamer',
    sa.Column('cmd', sa.String(length=256), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Screamer')),
    sa.UniqueConstraint('id', name=op.f('uq_Screamer_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Screamer')
    # ### end Alembic commands ###
