"""v2

Revision ID: 8c9df9ec829a
Revises: fe38ac74cfdc
Create Date: 2025-09-13 23:36:46.530637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import orm
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '8c9df9ec829a'
down_revision: Union[str, Sequence[str], None] = 'fe38ac74cfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_state',
    sa.Column('initialized', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_state')),
    sa.UniqueConstraint('id', name=op.f('uq_db_state_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(text("INSERT INTO db_state VALUES (1, 1)"))

    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.alter_column('cmd',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    with op.batch_alter_table('Transaction', schema=None) as batch_op:
        batch_op.alter_column('to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('Transaction', schema=None) as batch_op:
        batch_op.alter_column('to_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Screamer', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('cmd',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    op.drop_table('db_state')
    # ### end Alembic commands ###
