"""v11

Revision ID: b81213f0cc40
Revises: 394260c81df6
Create Date: 2026-09-10 14:26:05.327720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81213f0cc40'
down_revision: Union[str, Sequence[str], None] = '394260c81df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cache',
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Cache')),
    sa.UniqueConstraint('id', name=op.f('uq_Cache_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('Cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Cache_fresh_until'), ['fresh_until'], unique=False)

    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Msg_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Msg_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Msg_message_thread_id'), ['message_thread_id'], unique=False)

    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_in_block', sa.JSON(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('blocks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('priorities', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Queue_msg_id'), ['msg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Queue_msg_next_id'), ['msg_next_id'], unique=False)

    with op.batch_alter_table('QueueUser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QueueUser', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('block')

    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Queue_msg_next_id'))
        batch_op.drop_index(batch_op.f('ix_Queue_msg_id'))
        batch_op.drop_column('priorities')
        batch_op.drop_column('blocks')
        batch_op.drop_column('max_in_block')

    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Msg_message_thread_id'))
        batch_op.drop_index(batch_op.f('ix_Msg_message_id'))
        batch_op.drop_index(batch_op.f('ix_Msg_chat_id'))

    with op.batch_alter_table('Cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Cache_fresh_until'))

    op.drop_table('Cache')
    # ### end Alembic commands ###
