"""v10

Revision ID: 394260c81df6
Revises: c31bca3ed12f
Create Date: 2026-03-25 14:42:50.253793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394260c81df6'
down_revision: Union[str, Sequence[str], None] = 'c31bca3ed12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
