"""v9

Revision ID: c31bca3ed12f
Revises: ea913ff7d4ce
Create Date: 2026-03-24 15:46:42.147816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31bca3ed12f'
down_revision: Union[str, Sequence[str], None] = 'ea913ff7d4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clear_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cleared_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Queue', schema=None) as batch_op:
        batch_op.drop_column('cleared_at')
        batch_op.drop_column('clear_at')

    # ### end Alembic commands ###
